# Generated by Django 5.1.1 on 2024-10-02 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.CharField(max_length=255, verbose_name='Processor')),
                ('cpu', models.CharField(max_length=255, verbose_name='CPU')),
                ('vidio_card', models.CharField(max_length=255, verbose_name='Vidio Card')),
                ('screen', models.CharField(max_length=255, verbose_name='Screen')),
            ],
            options={
                'verbose_name': 'Computer',
                'verbose_name_plural': 'Computer',
            },
        ),
        migrations.CreateModel(
            name='CoursePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_time', models.CharField(max_length=255, verbose_name='Course Time')),
                ('theory', models.CharField(max_length=255, verbose_name='Theory')),
                ('theory_desc', models.CharField(max_length=255, verbose_name='Theory Time')),
                ('practice', models.CharField(max_length=255, verbose_name='Practice')),
                ('practice_desc', models.CharField(max_length=255, verbose_name='Practice Time')),
            ],
            options={
                'verbose_name': 'CoursePlan',
                'verbose_name_plural': 'CoursePlan',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.TextField(max_length=255, verbose_name='Place')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experience',
            },
        ),
        migrations.CreateModel(
            name='ForWho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'ForWho',
                'verbose_name_plural': 'ForWhos',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
            },
        ),
        migrations.CreateModel(
            name='WorkedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='course/icons', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'WorkedPlace',
                'verbose_name_plural': 'WorkedPlace',
            },
        ),
        migrations.CreateModel(
            name='AboutTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='course/about', verbose_name='Image')),
                ('experience', models.ManyToManyField(to='course.experience', verbose_name='Experience')),
                ('work_place', models.ManyToManyField(to='course.workedplace', verbose_name='Work place')),
            ],
            options={
                'verbose_name': 'AboutTeacher',
                'verbose_name_plural': 'AboutTeacher',
            },
        ),
        migrations.CreateModel(
            name='Modul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson', verbose_name='Lesson')),
            ],
            options={
                'verbose_name': 'Modul',
                'verbose_name_plural': 'Moduls',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('desc', models.TextField(verbose_name='Description')),
                ('icon', models.FileField(upload_to='course/icons', verbose_name='Icon')),
                ('about_computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.computer', verbose_name='AboutComputer')),
                ('about_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.aboutteacher', verbose_name='AboutTeacher')),
                ('course_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courseplan', verbose_name='CoursePlan')),
                ('for_who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.forwho', verbose_name='ForWho')),
                ('modul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.modul', verbose_name='Modul')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Course',
            },
        ),
    ]
