# Generated by Django 5.1.1 on 2024-10-02 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='number')),
                ('desc', models.TextField(verbose_name='description')),
            ],
            options={
                'verbose_name': 'ExtraDesc',
                'verbose_name_plural': 'ExtraDesc',
            },
        ),
        migrations.CreateModel(
            name='FutureProfession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Profession name')),
                ('desc', models.TextField(verbose_name='description')),
                ('image_icon', models.FileField(upload_to='future_professions/', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'FutureProfession',
                'verbose_name_plural': 'FutureProfession',
            },
        ),
        migrations.CreateModel(
            name='ProfessionPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='profession_partner/', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'ProfessionPartner',
                'verbose_name_plural': 'ProfessionPartner',
            },
        ),
        migrations.CreateModel(
            name='StudentComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('image', models.ImageField(upload_to='student_comments/', verbose_name='image')),
                ('profession', models.CharField(max_length=100, verbose_name='profession')),
                ('desc', models.TextField(verbose_name='description')),
            ],
            options={
                'verbose_name': 'StudentComments',
                'verbose_name_plural': 'StudentComments',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Teacher's name")),
                ('profession', models.CharField(max_length=100, verbose_name='profession')),
                ('position', models.CharField(max_length=100, verbose_name='position')),
            ],
            options={
                'verbose_name': 'Teachers',
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='WhyUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='image')),
                ('desc', models.TextField(verbose_name='description')),
            ],
            options={
                'verbose_name': 'WhyUs',
                'verbose_name_plural': 'WhyUs',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profession/', verbose_name='image')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('desc', models.TextField(verbose_name='description')),
                ('extra_desc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.extradesc', verbose_name='extra_desc')),
            ],
            options={
                'verbose_name': 'Profession',
                'verbose_name_plural': 'Profession',
            },
        ),
    ]
